### ISSUE TITLE
Print out a TODO list

### ISSUE THREAD

**Issue by iamnewton** [chrisopedia/eighth-inning#5]
- [ ] authorize marked2
- [ ] authorize alfred
- [ ] authorize dash
- [ ] import dash libraries
- [ ] download mac apps (list them out)
- [ ] download ksdiff?
- [ ] setup lagr
- [ ] authorize macaw
- [ ] ctags
- [ ] setup ssh config
- [ ] install alfred workflows?
